<?php

declare(strict_types=1);

namespace Horizon\Database\Factories;

use Closure;
use Faker\Factory as FakerFactory;
use Faker\Generator as Faker;
use Horizon\Database\Eloquent\Model;
use Horizon\Support\Collection;
use InvalidArgumentException;

/**
 * Model Factory
 * 
 * Generates model instances with fake data for testing and seeding.
 */
abstract class Factory
{
    /**
     * The name of the factory's corresponding model.
     */
    protected string $model;

    /**
     * The number of models that should be generated.
     */
    protected int $count = 1;

    /**
     * The state transformations that will be applied to the model.
     */
    protected array $states = [];

    /**
     * The "after creating" callbacks that will be applied to the model.
     */
    protected array $afterCreating = [];

    /**
     * The "after making" callbacks that will be applied to the model.
     */
    protected array $afterMaking = [];

    /**
     * The Faker instance for the builder.
     */
    protected Faker $faker;

    /**
     * The factory connection name.
     */
    protected ?string $connection = null;

    /**
     * Create a new factory instance.
     */
    public function __construct(?int $count = null, ?Collection $states = null, ?Collection $has = null, ?Collection $for = null, ?Collection $afterMaking = null, ?Collection $afterCreating = null, string $connection = null)
    {
        $this->count = $count ?? $this->count;
        $this->states = $states ? $states->all() : [];
        $this->afterMaking = $afterMaking ? $afterMaking->all() : [];
        $this->afterCreating = $afterCreating ? $afterCreating->all() : [];
        $this->connection = $connection;
        $this->faker = FakerFactory::create();
    }

    /**
     * Define the model's default state.
     */
    abstract public function definition(): array;

    /**
     * Get the name of the model that is generated by the factory.
     */
    public function modelName(): string
    {
        $resolver = static::$modelNameResolver ?: function (self $factory) {
            $namespacedFactoryBasename = Str::replaceLast(
                'Factory', '', Str::replaceFirst(static::$namespace, '', get_class($factory))
            );

            $factoryBasename = Str::replaceLast('Factory', '', class_basename(get_class($factory)));

            if ($factoryBasename === $namespacedFactoryBasename) {
                return static::$namespace.$factoryBasename;
            }

            return static::$namespace.$namespacedFactoryBasename;
        };

        return $this->model ?? $resolver($this);
    }

    /**
     * Create a new instance of the factory builder with the given mutated properties.
     */
    protected function newInstance(array $arguments = []): static
    {
        return new static(...array_values(array_merge([
            'count' => $this->count,
            'states' => Collection::make($this->states),
            'has' => Collection::make([]),
            'for' => Collection::make([]),
            'afterMaking' => Collection::make($this->afterMaking),
            'afterCreating' => Collection::make($this->afterCreating),
            'connection' => $this->connection,
        ], $arguments)));
    }

    /**
     * Set the amount of models you wish to create / make.
     */
    public function count(?int $count): static
    {
        if ($count === null) {
            return $this->newInstance(['count' => $this->count]);
        }

        return $this->newInstance(['count' => $count]);
    }

    /**
     * Set the states to be applied to the model.
     */
    public function state($states): static
    {
        return $this->newInstance([
            'states' => Collection::make($this->states)->merge(
                is_callable($states) ? [$states] : $states
            ),
        ]);
    }

    /**
     * Set the connection name on the model instance.
     */
    public function connection(string $connection): static
    {
        return $this->newInstance(['connection' => $connection]);
    }

    /**
     * Add a new "after making" callback to the model definition.
     */
    public function afterMaking(Closure $callback): static
    {
        return $this->newInstance([
            'afterMaking' => Collection::make($this->afterMaking)->push($callback),
        ]);
    }

    /**
     * Add a new "after creating" callback to the model definition.
     */
    public function afterCreating(Closure $callback): static
    {
        return $this->newInstance([
            'afterCreating' => Collection::make($this->afterCreating)->push($callback),
        ]);
    }

    /**
     * Create a collection of models and persist them to the database.
     */
    public function create($attributes = [], ?Model $parent = null): Collection|Model
    {
        if (!empty($attributes)) {
            return $this->state($attributes)->create([], $parent);
        }

        $results = $this->make($attributes, $parent);

        if ($results instanceof Model) {
            $this->store(Collection::make([$results]));

            $this->callAfterCreating(Collection::make([$results]), $parent);
        } else {
            $this->store($results);

            $this->callAfterCreating($results, $parent);
        }

        return $results;
    }

    /**
     * Set the creation attributes explicitly.
     */
    public function createOne($attributes = []): Model
    {
        return $this->count(1)->create($attributes);
    }

    /**
     * Create a collection of models.
     */
    public function createMany(iterable $records): Collection
    {
        return Collection::make($records)->map(function ($record) {
            return $this->create($record);
        });
    }

    /**
     * Make a collection of models.
     */
    public function make($attributes = [], ?Model $parent = null): Collection|Model
    {
        if (!empty($attributes)) {
            return $this->state($attributes)->make([], $parent);
        }

        if ($this->count === 1) {
            return tap($this->makeInstance($parent), function ($instance) use ($parent) {
                $this->callAfterMaking(Collection::make([$instance]), $parent);
            });
        }

        $instances = Collection::make(range(1, $this->count))->map(function () use ($parent) {
            return $this->makeInstance($parent);
        });

        $this->callAfterMaking($instances, $parent);

        return $instances;
    }

    /**
     * Make an instance of the model with the given attributes.
     */
    protected function makeInstance(?Model $parent = null): Model
    {
        return Model::unguarded(function () use ($parent) {
            return tap($this->newModel($this->getExpandedAttributes($parent)), function ($instance) {
                if (isset($this->connection)) {
                    $instance->setConnection($this->connection);
                }
            });
        });
    }

    /**
     * Get a raw attributes array for the model.
     */
    protected function getRawAttributes(?Model $parent = null): array
    {
        return $this->expandAttributes($this->definition());
    }

    /**
     * Get the expanded attributes for the model.
     */
    protected function getExpandedAttributes(?Model $parent = null): array
    {
        return $this->expandAttributes(
            $this->mergeAttributesFromParent($this->getRawAttributes($parent), $parent)
        );
    }

    /**
     * Merge attributes from the parent model.
     */
    protected function mergeAttributesFromParent(array $attributes, ?Model $parent): array
    {
        if ($parent) {
            $parentAttributes = $parent->getAttributes();
            
            // Here you could implement logic to merge parent attributes
            // For example, automatically set foreign keys
        }
        
        return $attributes;
    }

    /**
     * Expand all attributes to their underlying values.
     */
    protected function expandAttributes(array $definition): array
    {
        return collect($definition)->map(function ($attribute, $key) {
            if (is_callable($attribute) && !is_string($attribute) && !is_array($attribute)) {
                $attribute = $attribute($this->faker);
            }

            if ($attribute instanceof static) {
                $attribute = $attribute->create()->getKey();
            }

            if ($attribute instanceof Model) {
                $attribute = $attribute->getKey();
            }

            return $attribute;
        })->all();
    }

    /**
     * Run after making callbacks on a collection of models.
     */
    protected function callAfterMaking(Collection $instances, ?Model $parent = null): void
    {
        $instances->each(function ($instance) use ($parent) {
            foreach ($this->afterMaking as $callback) {
                $callback($instance, $this->faker);
            }
        });
    }

    /**
     * Run after creating callbacks on a collection of models.
     */
    protected function callAfterCreating(Collection $instances, ?Model $parent = null): void
    {
        $instances->each(function ($instance) use ($parent) {
            foreach ($this->afterCreating as $callback) {
                $callback($instance, $this->faker);
            }
        });
    }

    /**
     * Store a collection of models.
     */
    protected function store(Collection $results): void
    {
        $results->each(function (Model $model) {
            if (!$model->exists) {
                $model->save();
            }
        });
    }

    /**
     * Create a new model instance.
     */
    protected function newModel(array $attributes = []): Model
    {
        $model = $this->modelName();

        return new $model($attributes);
    }

    /**
     * Get the factory name resolver callback.
     */
    public static function guessFactoryNamesUsing(Closure $callback): void
    {
        static::$factoryNameResolver = $callback;
    }

    /**
     * Get the model name resolver callback.
     */
    public static function guessModelNamesUsing(Closure $callback): void
    {
        static::$modelNameResolver = $callback;
    }

    /**
     * Specify the callback that should be invoked to guess factory names.
     */
    protected static ?Closure $factoryNameResolver = null;

    /**
     * Specify the callback that should be invoked to guess model names.
     */
    protected static ?Closure $modelNameResolver = null;

    /**
     * The default namespace where factories reside.
     */
    protected static string $namespace = 'Database\\Factories\\';

    /**
     * Set the default namespace where factories reside.
     */
    public static function useNamespace(string $namespace): void
    {
        static::$namespace = $namespace;
    }

    /**
     * Get a new Faker instance.
     */
    protected function withFaker(): Faker
    {
        return $this->faker;
    }
}